version: "3.8"

services:
  qdrant:
    image: qdrant/qdrant:latest
    container_name: qdrant
    environment:
      QDRANT__SERVICE__API_KEY: tu_contraseña_32_caracteres
    deploy:
      mode: replicated
      replicas: 1
      placement:
        constraints:
          - node.role == manager
      resources:
        limits:
          cpus: '0.5'
          memory: 512M
      labels:
        - traefik.enable=true
        - traefik.http.routers.qdrant.rule=Host(`tu-subdominio.com`)
        - traefik.http.routers.qdrant.entrypoints=websecure
        - traefik.http.routers.qdrant.tls.certresolver=le
        - traefik.http.services.qdrant.loadbalancer.server.port=6333
    ports:
      - "6333:6333" 
    volumes:
      - qdrant_data:/qdrant/storage
    networks:
      - traefik_public
      - general_network

volumes:
  qdrant_data:
    driver: local

networks:
  traefik_public:
    external: true
  general_network:
    external: true
